INSERT INTO public.cidade(
	codigo_cidade, nome, pais)
	VALUES ('SAO', 'São Paulo', 'Brasil'), 
	       ('RIO', 'Rio de Janeiro', 'Brasil'), 
	       ('BUE', 'Buenos Aires', 'Argentina'), 
	       ('BSB', 'Brasília', 'Brasil'),  
	       ('CWB', 'Curitiba', 'Brasil'), 
	       ('BHZ', 'Belo Horizonte', 'Brasil'), 
	       ('FLN', 'Florianópolis', 'Brasil'), 
	       ('SSA', 'Salvador', 'Brasil'), 
	       ('FOR', 'Fortaleza', 'Brasil'), 
	       ('SCL', 'Santiago', 'Chile'), 
	       ('NYC', 'Nova York', 'Estados Unidos da América'), 
	       ('MEX', 'Cidade do México', 'México'), 
	       ('GDL', 'Guadalajara', 'México'), 
	       ('LON', 'Londres', 'Reino Unido'), 
	       ('LDB', 'Londrina', 'Brasil'), 
	       ('LIS', 'Lisboa', 'Portugal'), 
	       ('PAR', 'Paris', 'França'), 
	       ('DXB', 'Dubai', 'Emirados Árabes Unidos'), 
	       ('WAS', 'Washington, D.C.', 'Estados Unidos da América'), 
	       ('ATL', 'Atlanta', 'Estados Unidos da América'), 
	       ('TYO', 'Tóquio', 'Japão'),
	       ('DEN', 'Denver', 'Estados Unidos da América');
